// Global using directives

global using System;
global using System.Collections.Generic;
global using System.Security.Claims;
global using System.Threading.Tasks;
global using IdentityServer4.Models;
global using Microsoft.Extensions.DependencyInjection;
global using Volo.Abp;
global using Volo.Abp.Authorization;
global using Volo.Abp.Authorization.Permissions;
global using Volo.Abp.Autofac;
global using Volo.Abp.BackgroundJobs;
global using Volo.Abp.Data;
global using Volo.Abp.DependencyInjection;
global using Volo.Abp.Guids;
global using Volo.Abp.IdentityServer;
global using Volo.Abp.IdentityServer.ApiResources;
global using Volo.Abp.IdentityServer.ApiScopes;
global using Volo.Abp.IdentityServer.Clients;
global using Volo.Abp.IdentityServer.IdentityResources;
global using Volo.Abp.Modularity;
global using Volo.Abp.MultiTenancy;
global using Volo.Abp.PermissionManagement;
global using Volo.Abp.Security.Claims;
global using Volo.Abp.Testing;
global using Volo.Abp.Threading;
global using Volo.Abp.Uow;
global using ApiResource = Volo.Abp.IdentityServer.ApiResources.ApiResource;
global using ApiScope = Volo.Abp.IdentityServer.ApiScopes.ApiScope;
global using Client = Volo.Abp.IdentityServer.Clients.Client;