// Global using directives

global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using IdentityModel;
global using IdentityServer4.Models;
global using Lion.AbpPro.DataDictionaryManagement;
global using Lion.AbpPro.Extension.System;
global using Lion.AbpPro.FileManagement;
global using Lion.AbpPro.Localization;
global using Lion.AbpPro.MultiTenancy;
global using Lion.AbpPro.NotificationManagement;
global using Lion.AbpPro.Users.Dto;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
global using Volo.Abp;
global using Volo.Abp.AuditLogging;
global using Volo.Abp.Authorization.Permissions;
global using Volo.Abp.AutoMapper;
global using Volo.Abp.BackgroundJobs;
global using Volo.Abp.Data;
global using Volo.Abp.DependencyInjection;
global using Volo.Abp.Domain.Services;
global using Volo.Abp.Emailing;
global using Volo.Abp.EventBus.Distributed;
global using Volo.Abp.FeatureManagement;
global using Volo.Abp.Guids;
global using Volo.Abp.Identity;
global using Volo.Abp.IdentityServer;
global using Volo.Abp.IdentityServer.ApiResources;
global using Volo.Abp.IdentityServer.ApiScopes;
global using Volo.Abp.IdentityServer.Clients;
global using Volo.Abp.IdentityServer.IdentityResources;
global using Volo.Abp.Localization;
global using Volo.Abp.Modularity;
global using Volo.Abp.MultiTenancy;
global using Volo.Abp.ObjectMapping;
global using Volo.Abp.PermissionManagement;
global using Volo.Abp.PermissionManagement.Identity;
global using Volo.Abp.PermissionManagement.IdentityServer;
global using Volo.Abp.SettingManagement;
global using Volo.Abp.Settings;
global using Volo.Abp.TenantManagement;
global using Volo.Abp.Uow;
global using ApiResource = Volo.Abp.IdentityServer.ApiResources.ApiResource;
global using ApiScope = Volo.Abp.IdentityServer.ApiScopes.ApiScope;
global using Client = Volo.Abp.IdentityServer.Clients.Client;
global using IdentityResource = Volo.Abp.IdentityServer.IdentityResources.IdentityResource;